---
postgres:
  database: attendance_db
  host: some-postgres.database.svc.cluster.local
  port: 5432
  user: postgres
  password: password

redis:
  host: some-redis.database.svc.cluster.local
  port: 6379
  password: ""
